services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "8787:8787"
    environment:
      - NODE_ENV=production
      - PORT=8787
      - DEFAULT_LANG=en
      # Add your API keys here or use .env file
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENSUBTITLES_API_KEY=${OPENSUBTITLES_API_KEY}
      - CORS_ORIGIN=${CORS_ORIGIN:-""}
    env_file:
      - .env.example
    restart: unless-stopped

  addon:
    build:
      context: .
      dockerfile: addon.Dockerfile
    ports:
      - "7000:7000"
    environment:
      - NODE_ENV=production
      - BACKEND_URL=http://server:8787/subs
      - DEFAULT_LANG=en
    depends_on:
      - server
    restart: unless-stopped